# Generated by Django 4.0.3 on 2022-04-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_end_report_delete_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='end_report',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
